In [225]:
import numpy as np

### Creating Numpy Arrays from Python Lists

In [226]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [227]:
np.array([3.14, 2, 3, 4])

array([3.14, 2.  , 3.  , 4.  ])

In [228]:
np.array([1, 2, 3, 4], dtype=float)

array([1., 2., 3., 4.])

In [229]:
a1 = np.array([1, 2, 3, 4])
print(type(a1))   
print(a1.shape)
print(a1.size)  
print(a1.ndim)                                      

<class 'numpy.ndarray'>
(4,)
4
1


In [230]:
a2 = np.array([[1, 2, 3], [4, 5, 6]])
print(type(a2))
print(a2.shape)
print(a2.size)
print(a2.ndim)

<class 'numpy.ndarray'>
(2, 3)
6
2


### Creating Numpy Arrays from Scratch

#### `zeros`

In [231]:
np.zeros((2, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [232]:
np.zeros((2, 4)).dtype

dtype('float64')

In [233]:
np.zeros((2, 4), dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

#### `ones`

In [234]:
np.ones((3, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [235]:
np.ones((3, 5), dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

#### `arange`

In [236]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

#### `full`

In [237]:
np.full((3, 5), 6.9)

array([[6.9, 6.9, 6.9, 6.9, 6.9],
       [6.9, 6.9, 6.9, 6.9, 6.9],
       [6.9, 6.9, 6.9, 6.9, 6.9]])

#### `linspace`

In [238]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

#### `rand`

In [239]:
# seed for reproducibility
np.random.seed(0)

In [240]:
np.random.random((4, 4))

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ],
       [0.96366276, 0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606, 0.0871293 ]])

In [241]:
np.random.normal(0, 1, size=(3, 3))

array([[ 0.44386323,  0.33367433,  1.49407907],
       [-0.20515826,  0.3130677 , -0.85409574],
       [-2.55298982,  0.6536186 ,  0.8644362 ]])

In [242]:
np.random.randint(0, 9, size=(3, 4)) #[0, 9)

array([[7, 2, 0, 0],
       [4, 5, 5, 6],
       [8, 4, 1, 4]], dtype=int32)

In [243]:
np.random.rand(4, 4)

array([[0.6818203 , 0.3595079 , 0.43703195, 0.6976312 ],
       [0.06022547, 0.66676672, 0.67063787, 0.21038256],
       [0.1289263 , 0.31542835, 0.36371077, 0.57019677],
       [0.43860151, 0.98837384, 0.10204481, 0.20887676]])

### Array Indexing & Slicing

#### `One-dimensional subarray`

In [244]:
x1 = np.random.randint(0, 20, 6)
print(x1)

[ 3 12  4  8 14 15]


In [245]:
x1[4], x1[0], x1[-1]

(np.int32(14), np.int32(3), np.int32(15))

#### `Multi-demensional subarray`

In [246]:
x2 = np.random.randint(0, 10, size=(3, 4))
print(x2)

[[4 3 7 5]
 [5 0 1 5]
 [9 3 0 5]]


In [247]:
x2[1, 3]

np.int32(5)

In [248]:
x2[1, 3] = 1000
print(x2)

[[   4    3    7    5]
 [   5    0    1 1000]
 [   9    3    0    5]]


#### `Slicing`
x[start:stop:step]

In [249]:
x1

array([ 3, 12,  4,  8, 14, 15], dtype=int32)

In [250]:
x1[0:3]

array([ 3, 12,  4], dtype=int32)

In [251]:
x1[2:4]

array([4, 8], dtype=int32)

In [252]:
# every other element, every 2 step
x1[::2]

array([ 3,  4, 14], dtype=int32)

In [253]:
x2

array([[   4,    3,    7,    5],
       [   5,    0,    1, 1000],
       [   9,    3,    0,    5]], dtype=int32)

In [254]:
# two rows, three columns
x2[:2, :3]

array([[4, 3, 7],
       [5, 0, 1]], dtype=int32)

In [255]:
x2[:, :2]

array([[4, 3],
       [5, 0],
       [9, 3]], dtype=int32)

### Comparison operators

In [256]:
scores = np.array([91, 55, 100, 73, 82, 64])

In [257]:
scores == 100

array([False, False,  True, False, False, False])

In [258]:
scores >= 60

array([ True, False,  True,  True,  True,  True])

In [259]:
scores[scores < 60] = 0
scores

array([ 91,   0, 100,  73,  82,  64])

### Reshaping of Arrays & Transpose

#### `reshape`

In [260]:
grid = np.arange(1, 10)
grid.shape

(9,)

In [261]:
grid.reshape(3, 3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [262]:
x = np.array([1, 2, 3])
x.shape

(3,)

In [263]:
x.reshape(1, 3).shape

(1, 3)

#### `Transpose`

In [264]:
x = np.array([[1, 2], [3, 4]])
print(x)

[[1 2]
 [3 4]]


In [265]:
x.T

array([[1, 3],
       [2, 4]])

### Array Concatenation Splitting

#### `concatenate`

In [266]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])

In [267]:
np.concatenate((x, y)) # defual axis=0 (axis=0 => rows, axis=1 => cols)

array([1, 2, 3, 3, 2, 1])

In [268]:
grid = np.array([[1, 2, 3],
                  [4, 5, 6]])
print(grid)

[[1 2 3]
 [4 5 6]]


In [269]:
np.concatenate((grid, grid), axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [270]:
np.concatenate((grid, grid), axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

#### `vstack(vertical stack)`

In [271]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7], [6, 5, 4]])

In [272]:
np.vstack((x, grid))

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

#### `hstack(horizontal stack)`

In [273]:
y = np.array([[99], [99]])
np.hstack((y, grid))

array([[99,  9,  8,  7],
       [99,  6,  5,  4]])

#### `Splitting of arrays`

In [274]:
x = np.array([1, 2, 3, 99, 69, 3, 2, 1])

In [275]:
x1, x2, x3 = np.split(x, [3, 5])

### Broadcasting and Vectorized operations
Broadcasting is simply a set of rules for applying binary ufuncs (e.g., addition, subtraction, mulplication, divison, etc.) on arrays of different sizes
<p align="center">
  <img src="Images/broadcasting.png" alt="example">
</p>


In [276]:
a = np.arange(3) # [0, 1, 2]
a + 5 # Broadcasting

array([5, 6, 7])

In [277]:
b = np.ones((3, 3))

In [278]:
b.shape, a.shape

((3, 3), (3,))

In [279]:
b + a

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [280]:
a.reshape(3, 1) + a

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

### Manipulating & Compating Arrays

#### `Aggregation`

In [281]:
list_number = [1, 2, 3]

In [282]:
ll = np.array(list_number)

In [283]:
sum(ll) # Pyyhon sum

np.int64(6)

In [284]:
np.sum(ll) # Numpy sum

np.int64(6)

In [285]:
# Create a massive Numpy array
massive_array = np.random.random(10000)

In [ ]:
%timeit sum(massive_array)
%timeit np.sum(massive_array)

In [ ]:
np.max(massive_array)

np.float64(0.9999709462497284)

In [ ]:
np.min(massive_array)

np.float64(2.0027530115096503e-05)

#### `Math & Arithmetic`

In [ ]:
a = np.array([1, 2, 3])
b = np.array([3, 2, 1])

In [ ]:
np.add(a, b) # a + b

array([4, 4, 4])

In [ ]:
np.subtract(a, b) # a - b

array([-2,  0,  2])

In [ ]:
np.multiply(a, b) # a * b

array([3, 4, 3])

In [ ]:
np.divide(a, b) # a / b

array([0.33333333, 1.        , 3.        ])

In [ ]:
np.divmod(a, b) # a // b

(array([0, 1, 3]), array([1, 0, 0]))

In [ ]:
np.power(a, 2) # a ** 2

array([1, 4, 9])

In [ ]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081])

In [ ]:
np.exp(a)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [ ]:
np.log(a)

array([0.        , 0.69314718, 1.09861229])

In [ ]:
np.abs(a)

array([1, 2, 3])

In [ ]:
epsilon = 1e-15
"""
np.clip() is used to limit the values in an array to a specified range.
"""
np.clip(a, epsilon, 1 - epsilon)

array([1., 1., 1.])

### Sorting Arrays
np.sort() uses an quick sort algorithm

In [ ]:
x = np.array([2, 1, 4, 3, 5])
np.sort(x)

array([1, 2, 3, 4, 5])

In [ ]:
# a related function is argsort, which instead returns the indices of the sorted elements
np.argsort(x)

array([1, 0, 3, 2, 4])

#### `Sorting along rows or columns`
NumPy's sorting algorithm is the ability to sort along speccific rows or columns of a multidimensional array using the axis argument

In [ ]:
np.random.seed(42)

MatA = np.random.randint(0, 10, size=(4, 5))

In [ ]:
MatA

array([[6, 3, 7, 4, 6],
       [9, 2, 6, 7, 4],
       [3, 7, 7, 2, 5],
       [4, 1, 7, 5, 1]], dtype=int32)

In [ ]:
np.sort(MatA, axis=0)

array([[3, 1, 6, 2, 1],
       [4, 2, 7, 4, 4],
       [6, 3, 7, 5, 5],
       [9, 7, 7, 7, 6]], dtype=int32)

In [ ]:
np.sort(MatA, axis=1)

array([[3, 4, 6, 6, 7],
       [2, 4, 6, 7, 9],
       [2, 3, 5, 7, 7],
       [1, 1, 4, 5, 7]], dtype=int32)

### Distribution

#### `Uniform Distribution`

In [ ]:
np.random.uniform(low=0.0, high=1.0, size=(3, 4))

array([[0.18182497, 0.18340451, 0.30424224, 0.52475643],
       [0.43194502, 0.29122914, 0.61185289, 0.13949386],
       [0.29214465, 0.36636184, 0.45606998, 0.78517596]])

#### `Normal Distribution`

In [ ]:
np.random.normal(loc=0.0, scale=1.0, size=(3, 4))

array([[ 0.0675282 , -1.42474819, -0.54438272,  0.11092259],
       [-1.15099358,  0.37569802, -0.60063869, -0.29169375],
       [-0.60170661,  1.85227818, -0.01349722, -1.05771093]])

#### `Exponential Distribution`

In [ ]:
np.random.exponential(3.0, size=(3, 4))

array([[ 0.10498116,  7.20126866,  0.89837333,  3.2587674 ],
       [ 1.12063974,  2.20233269,  2.37367139,  0.6131658 ],
       [10.4784214 ,  4.47673613,  8.41528326,  6.75645599]])

#### `Binomial Distribution`

In [ ]:
np.random.binomial(10, 0.5, size=5)

array([5, 7, 3, 4, 2], dtype=int32)

#### `Poisson Distribution`

In [ ]:
np.random.poisson(3.0, size=5)

array([2, 3, 2, 3, 4], dtype=int32)

### Statistics

In [ ]:
np.mean(massive_array)

np.float64(0.5014071673347639)

In [ ]:
np.var(massive_array)

np.float64(0.08264590341248054)

In [ ]:
np.std(massive_array)

np.float64(0.2874820053716068)

In [ ]:
np.cov(massive_array)

array(0.08265417)

In [ ]:
np.corrcoef(massive_array)

np.float64(1.0)

### Linear Algebra

In [ ]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[6, 5], [4, 3], [2, 1]])

In [ ]:
print(A.shape)
print(B.shape)

(3, 3)
(3, 2)


In [ ]:
np.dot(A, B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [ ]:
B.T

array([[6, 4, 2],
       [5, 3, 1]])

In [ ]:
B.T @ A

array([[36, 48, 60],
       [24, 33, 42]])

In [ ]:
A = np.array([[1, 2], [3, 4]])

In [ ]:
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [ ]:
np.linalg.det(A)

np.float64(-2.0000000000000004)

In [ ]:
eig_vals, eigvecs = np.linalg.eig(A)
print(eig_vals)
print(eigvecs)

[-0.37228132  5.37228132]
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


### Dot Product Example

In [ ]:
import pandas as pd

In [ ]:
np.random.seed(0)

In [ ]:
sales_amounts = np.random.randint(20, size=(5, 3))
print(sales_amounts)

[[12 15  0]
 [ 3  3  7]
 [ 9 19 18]
 [ 4  6 12]
 [ 1  6  7]]


In [ ]:
weekly_sales = pd.DataFrame(sales_amounts, index=["Mon", "Tues", "Wed", "Thurs", "Fri"], 
                            columns=["Almond Butter", "Peanut Butter", "Cashew Butter"])

In [ ]:
print(weekly_sales)

       Almond Butter  Peanut Butter  Cashew Butter
Mon               12             15              0
Tues               3              3              7
Wed                9             19             18
Thurs              4              6             12
Fri                1              6              7


In [ ]:
# create a price array
prices = np.array([10, 8, 12])

In [ ]:
butter_prices = pd.DataFrame(prices.reshape(1, 3), index=["Price"], columns=["Almond Butter", "Peanut Butter", "Cashew Butter"])

In [ ]:
print(butter_prices)

       Almond Butter  Peanut Butter  Cashew Butter
Price             10              8             12


In [ ]:
weekly_sales.shape, butter_prices.shape

((5, 3), (1, 3))

In [ ]:
total_prices = np.dot(weekly_sales, butter_prices.T)

In [ ]:
weekly_sales["Total prices"] = total_prices
print(weekly_sales)

       Almond Butter  Peanut Butter  Cashew Butter  Total prices
Mon               12             15              0           240
Tues               3              3              7           138
Wed                9             19             18           458
Thurs              4              6             12           232
Fri                1              6              7           142
