In [32]:
import numpy as np

1. Tạo mảng 1 chiều
Yêu cầu: Tạo mảng NumPy 1 chiều gồm các số từ 0 đến 9.

In [33]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [34]:
arr = np.linspace(0, 9, 10, dtype=int)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


2. Tạo mảng 2 chiều
Yêu cầu: Tạo mảng 2 chiều (3x3) với giá trị từ 1 đến 9.

In [35]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [36]:
arr = np.arange(1, 10).reshape(3, 3)
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


3. Truy cập phần tử
Yêu cầu: Truy cập phần tử ở hàng 2, cột 3 trong mảng 2 chiều.

In [37]:
arr = np.arange(12).reshape(3, 4)
print(arr[2, 3])

11


4. Cắt mảng
Yêu cầu: Cắt lấy hàng đầu tiên của mảng 2 chiều.

In [38]:
arr[0, :]

array([0, 1, 2, 3])

5. Tính tổng các phần tử
Yêu cầu: Tính tổng các phần tử của mảng.

In [39]:
print(np.sum(arr))

66


6. Tạo mảng toàn số 0
Yêu cầu: Tạo mảng 4x4 toàn số 0.

In [40]:
arr = np.zeros((4, 4))
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


7. Mảng đơn vị
Yêu cầu: Tạo ma trận đơn vị kích thước 5x5.

In [41]:
arr = np.eye(5)
print(arr)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


8. Tạo mảng ngẫu nhiên
Yêu cầu: Tạo mảng 1 chiều gồm 10 số ngẫu nhiên từ 0 đến 1.

In [42]:
arr = np.random.rand(10)
print(arr)

[0.96797294 0.87132027 0.25264934 0.56731673 0.29074613 0.68904535
 0.81772782 0.7730931  0.23784503 0.27593357]


9. Đổi kích thước mảng
Yêu cầu: Chuyển mảng 1 chiều gồm 12 phần tử thành mảng 3x4.

In [43]:
arr = np.arange(12).reshape(3, 4)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


10. Tính dot product
Yêu cầu: Tính tích vô hướng (dot product) giữa hai vector 1 chiều.

In [44]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([7, 8, 9])
print(np.dot(a, b))

[ 50 122]


11. Norm của vector
Yêu cầu: Tính chuẩn (norm) của một vector.

In [53]:
arr = np.array([3, 4])
norm = np.linalg.norm(arr)
print(norm)

5.0


12. Determinant
Yêu cầu: Tính định thức của ma trận 3x3.

In [45]:
arr = np.random.rand(3, 3)
print(np.linalg.det(arr))

0.017894966797964058


13. Inverse của ma trận
Yêu cầu: Tính ma trận nghịch đảo của ma trận 2x2.

In [46]:
arr = np.array([[1, 2], [3, 4]])
print(np.linalg.inv(arr))

[[-2.   1. ]
 [ 1.5 -0.5]]


14. Broadcasting
Yêu cầu: Cộng một vector 1x3 vào ma trận 3x3 sử dụng broadcasting.

In [47]:
a = np.array([1, 2, 3])
b = np.arange(9).reshape(3, 3)
print(a + b)

[[ 1  3  5]
 [ 4  6  8]
 [ 7  9 11]]


15. Indexing nâng cao
Yêu cầu: Chọn ra các phần tử chẵn trong mảng 1 chiều.

In [57]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
even_numbers = arr[arr % 2 == 0]
print(even_numbers)

[2 4 6 8]


16. Tạo ma trận chéo
Yêu cầu: Tạo ma trận chéo từ vector [1, 2, 3, 4].

In [58]:
arr = np.arange(1, 5)
print(np.diag(arr))

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


17. So sánh hai mảng
Yêu cầu: So sánh hai mảng xem chúng có bằng nhau phần tử tương ứng
hay không.

In [49]:
a = np.array([1, 2, 3])
b = np.array([1, 2, 3])
print(a == b)

[ True  True  True]


18. Thay giá trị theo điều kiện
Yêu cầu: Thay mọi giá trị lớn hơn 5 trong mảng bằng 0.

In [63]:
arr = np.arange(15)
arr[arr > 5] = 0
print(arr)

[0 1 2 3 4 5 0 0 0 0 0 0 0 0 0]


19. Tính tổng theo cột
Yêu cầu: Tính tổng từng cột trong ma trận 3x3.

In [51]:
arr = np.arange(9).reshape(3, 3)
print(np.sum(arr, axis=0))

[ 9 12 15]


20. Tính trung bình từng hàng
Yêu cầu: Tính giá trị trung bình từng hàng của ma trận 3x4.

In [52]:
arr = np.arange(12).reshape(3, 4)
print(np.mean(arr, axis=1))

[1.5 5.5 9.5]
